# Generated by Django 4.1 on 2022-09-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_comment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='username',
            field=models.CharField(default='익명', max_length=50),
        ),
    ]
