# Generated by Django 4.1 on 2022-09-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='header',
            field=models.CharField(choices=[('기타', '기타'), ('잡담', '잡담'), ('유머', '유머'), ('게임', '게임'), ('일상', '일상')], default='기타', max_length=2),
        ),
    ]
