# Generated by Django 4.1 on 2022-09-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_up_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='up_check',
            field=models.CharField(default='익명', max_length=50),
        ),
    ]
