# Generated by Django 4.1 on 2022-09-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_up_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='upcheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_check', models.CharField(default='익명', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='up_check',
        ),
    ]
