# Generated by Django 4.1 on 2022-09-11 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_upcheck_remove_article_up_check'),
    ]

    operations = [
        migrations.DeleteModel(
            name='upcheck',
        ),
    ]
