# Generated by Django 4.1 on 2022-09-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_delete_upcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upcheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_check', models.CharField(default='익명', max_length=50)),
            ],
        ),
    ]
