# Generated by Django 4.1 on 2022-09-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_remove_comment_comment_count_article_comment_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usericon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_id', models.IntegerField()),
                ('iconname', models.CharField(max_length=20)),
                ('url', models.TextField()),
            ],
        ),
    ]
