# Generated by Django 4.1 on 2022-09-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_itembox'),
    ]

    operations = [
        migrations.AddField(
            model_name='usericon',
            name='price',
            field=models.IntegerField(default=500),
        ),
    ]
