# Generated by Django 4.1 on 2022-09-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_usericon_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='icon_url',
            field=models.TextField(default='icon/gunbbang.png'),
        ),
    ]
