# Generated by Django 4.1 on 2022-09-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_color',
            field=models.TextField(default='black'),
        ),
    ]
