# Generated by Django 4.1 on 2022-09-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0026_profile_id_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembox',
            name='color_name',
            field=models.TextField(default='black'),
        ),
    ]
