# Generated by Django 4.1 on 2022-09-25 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0027_itembox_color_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itembox',
            name='color_name',
        ),
    ]
