# Generated by Django 4.1 on 2022-09-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0029_colorbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title_color',
            field=models.TextField(default='black'),
        ),
    ]
