# Generated by Django 4.1 on 2022-09-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(choices=[('기타', '기타'), ('액션', '액션'), ('공포', '공포'), ('로맨스', '로맨스'), ('스릴러', '스릴러')], default='기타', max_length=10)),
                ('username', models.CharField(default='익명', max_length=16)),
                ('title', models.CharField(max_length=20)),
                ('score', models.FloatField()),
                ('content', models.TextField()),
                ('release_date', models.DateField()),
                ('count', models.IntegerField(default=0)),
                ('poster_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
