# Generated by Django 4.1 on 2022-09-18 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='header',
            new_name='genre',
        ),
    ]
